name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Main metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: hoangnv25
  
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Saigon
          config_display: large
  
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_colors: github
  
          plugin_achievements: yes
          plugin_achievements_threshold: C




  isometric:
    runs-on: ubuntu-latest
    steps:
      - name: Isometric commit calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: hoangnv25
  
          template: classic
          base: ""
          filename: isometric-calendar.svg
  
          config_display: large
  
          plugin_isocalendar: yes
          plugin_isocalendar_layout: horizontal
          plugin_isocalendar_duration: half-year




