name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Main metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: hoangnv25

          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Saigon

          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          plugin_languages_colors: github

          plugin_achievements: yes
          plugin_achievements_threshold: C

  isometric:
    runs-on: ubuntu-latest
    steps:
      - name: Isometric commit calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: hoangnv25

          template: classic
          base: ""
          filename: isometric-calendar.svg
          output_path: .

          plugin_isometric_calendar: yes
          plugin_isometric_calendar_duration: full-year


